export const RECEIVE_SPONSORS = 'RECEIVE_SPONSORS';
export const REQUEST_SPONSORS = 'REQUEST_SPONSORS';

export const RECEIVE_SPEAKERS = 'RECEIVE_SPEAKERS';
export const REQUEST_SPEAKERS = 'REQUEST_SPEAKERS';

export const RECEIVE_SESSIONS = 'RECEIVE_SESSIONS';
export const REQUEST_SESSIONS = 'REQUEST_SESSIONS';

export const RECEIVE_TRACKS = 'RECEIVE_TRACKS';
export const REQUEST_TRACKS = 'REQUEST_TRACKS';

export const RECEIVE_SUBMISSIONS = 'RECEIVE_SUBMISSIONS';
export const RECEIVE_AUDIENCES = 'RECEIVE_AUDIENCES';
export const RECEIVE_SPONSOR_LEVELS = 'RECEIVE_SPONSOR_LEVELS';

export const SET_CONFERENCE_YEAR = 'SET_CONFERENCE_YEAR';
export const SET_TRACK_INDEX = 'SET_TRACK_INDEX';
export const SET_TRACK_NAME = 'SET_TRACK_NAME';

export const SIDE_MENU_OPEN = 'SIDE_MENU_OPEN';
export const SIDE_MENU_CLOSE = 'SIDE_MENU_CLOSE';

export const MAX_YEARS_AGO = 10;
